print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")

print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")


print("GGGGGGGGGGGGG")

print("GGGGGGGGGGGGG")

print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")
print("GGGGGGGGGGGGG")